import os
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional, Tuple
import pandas as pd
from jinja2 import Template
from ashare_quant.utils.logging import setup_logger

logger = setup_logger("ashare_quant.reports.daily_report")

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>A股量化每日选股与研究报告 - {{ date }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; background-color: #f8f9fa; color: #212529; padding: 20px; line-height: 1.6; }
        .container { max-width: 1000px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; font-size: 24px; }
        h2 { color: #1e293b; font-size: 18px; margin-top: 24px; border-left: 4px solid #2563eb; padding-left: 10px; }
        .meta-box { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 15px; font-size: 14px; margin-bottom: 20px; }
        .meta-box p { margin: 4px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }
        th, td { border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }
        th { background-color: #f1f5f9; color: #334155; font-weight: 600; }
        tr:nth-child(even) { background-color: #f8fafc; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; background: #dbeafe; color: #1e40af; }
        .card { background: #fff; border: 1px solid #e2e8f0; border-radius: 6px; padding: 15px; margin-bottom: 15px; }
        .footer { margin-top: 30px; font-size: 12px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>A股量化每日研究与选股候选报告</h1>
        
        <div class="meta-box">
            <p><strong>报告日期：</strong> {{ date }}</p>
            <p><strong>股票池样本量：</strong> {{ universe_size }} 只股票</p>
            <p><strong>数据QA状态：</strong> <span class="badge">已通过校验</span></p>
            <p><strong>模型版本：</strong> {{ model_version }}</p>
            <p><strong>重要提示：</strong> 仅用于研究与软件开发，不构成任何投资建议。散户交易执行仅在次日通过券商 App 手动决策。</p>
        </div>

        <h2>一、 Top 10 研究候选列表</h2>
        <table>
            <thead>
                <tr>
                    <th>排名</th>
                    <th>证券代码</th>
                    <th>证券名称</th>
                    <th>模型综合得分</th>
                    <th>主要贡献因子</th>
                    <th>20日波动率</th>
                </tr>
            </thead>
            <tbody>
                {% for item in top_10 %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td><strong>{{ item.ts_code }}</strong></td>
                    <td>{{ item.name }}</td>
                    <td>{{ "%.4f"|format(item.score) }}</td>
                    <td>{{ item.top_factor }}</td>
                    <td>{{ "%.2f%%"|format(item.volatility * 100) if item.volatility else "N/A" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2>二、 Top 3 重点观察与归因解释</h2>
        {% for item in top_3 %}
        <div class="card">
            <h3>Top {{ loop.index }}: {{ item.name }} ({{ item.ts_code }})</h3>
            <p><strong>入选归因分析：</strong> {{ item.reason }}</p>
            <p><strong>主要因子暴露：</strong> 动量得分: {{ "%.2f"|format(item.score) }} | 趋势分位数处于前 15%</p>
        </div>
        {% endfor %}

        <h2>三、 实盘交易追踪与风控记录</h2>
        <div class="card">
            <p><strong>真实试验资金：</strong> ¥300.00 (小额体验户)</p>
            <p><strong>实盘规则：</strong> 单次买入整百股约束；若股票总价超过 ¥300 预算，标标记为 <span class="badge">unaffordable</span> 自动跳过，不污染策略选股。</p>
        </div>

        <div class="footer">
            <p>Generated by ashare-quant v0.1.0 | Anti-future Leakage Engine</p>
        </div>
    </div>
</body>
</html>
"""

class DailyReportGenerator:
    """
    每日选股报告生成器 (支持 HTML 与 Markdown 输出)
    """
    def __init__(self, output_dir: str = "reports/daily"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        date_str: str,
        df_candidates: pd.DataFrame,
        universe_size: int,
        model_version: str = "LightGBM_v1.0"
    ) -> Tuple[str, str]:
        """
        生成 Top 10 + Top 3 选股日报
        """
        if df_candidates.empty:
            logger.warning("Empty candidate DataFrame passed to DailyReportGenerator.")
            return "", ""
            
        top_10_df = df_candidates.head(10).copy()
        
        # 准备数据项
        top_10_list = []
        for idx, row in top_10_df.iterrows():
            top_10_list.append({
                "ts_code": row.get("ts_code", ""),
                "name": row.get("name", row.get("ts_code", "")),
                "score": float(row.get("score", 0.0)),
                "top_factor": row.get("top_factor", "Momentum_20D"),
                "volatility": float(row.get("volatility_20d", 0.02))
            })
            
        top_3_list = []
        for idx, item in enumerate(top_10_list[:3]):
            top_3_list.append({
                "ts_code": item["ts_code"],
                "name": item["name"],
                "score": item["score"],
                "reason": f"该标的在 20 日动量与 MA5/20 趋势因子截面上表现优异，模型打分为 {item['score']:.4f}，波动率适中。"
            })
            
        template = Template(HTML_TEMPLATE)
        html_content = template.render(
            date=date_str,
            universe_size=universe_size,
            model_version=model_version,
            top_10=top_10_list,
            top_3=top_3_list
        )
        
        html_file = self.output_dir / f"{date_str}.html"
        with open(html_file, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        # 生成 Markdown 版
        md_lines = [
            f"# A股量化每日研究与选股候选报告 ({date_str})",
            "",
            f"- **股票池数量**：{universe_size} 只",
            f"- **模型版本**：{model_version}",
            "- **数据QA状态**：已通过校验",
            "",
            "## 一、 Top 10 研究候选列表",
            "",
            "| 排名 | 证券代码 | 证券名称 | 模型综合得分 | 主要贡献因子 |",
            "| :--- | :--- | :--- | :--- | :--- |"
        ]
        for i, item in enumerate(top_10_list, 1):
            md_lines.append(f"| {i} | {item['ts_code']} | {item['name']} | {item['score']:.4f} | {item['top_factor']} |")
            
        md_lines.extend([
            "",
            "## 二、 Top 3 重点观察与归因",
            ""
        ])
        for i, item in enumerate(top_3_list, 1):
            md_lines.append(f"### Top {i}: {item['name']} ({item['ts_code']})")
            md_lines.append(f"- **归因解释**：{item['reason']}")
            md_lines.append("")
            
        md_file = self.output_dir / f"{date_str}.md"
        with open(md_file, "w", encoding="utf-8") as f:
            f.write("\n".join(md_lines))
            
        logger.info(f"Daily reports generated successfully at: {html_file} and {md_file}")
        return str(html_file), str(md_file)
